//! How a date, a time and an instant are written when a record leaves this
//! process.
//!
//! # The default is not a format
//!
//! `time`'s derived `Serialize` writes its own internal representation. An
//! `OffsetDateTime` becomes a nine-element array, a `Date` becomes
//! `[2026, 2]` — a year and an *ordinal day* — and a `Time` becomes
//! `[22, 0, 0, 0]`. They round-trip perfectly through `time`, which is why a
//! test that serialises and deserialises passes without noticing anything.
//!
//! Two things are wrong with that, and both matter for the artefact this
//! workspace exists to produce:
//!
//! - **A CDR is what two companies settle against.** A partner reading
//!   `"started_at": [2026, 2, 10, 0, 0, 0, 1, 0, 0]` cannot settle against it,
//!   and every wire this stack meets — OCPI, OCPP, OICP, EN 16931 — writes an
//!   instant as RFC 3339. A record only this codebase can read is not a record
//!   two parties hold.
//! - **The shape is a dependency's private business.** Nothing promises it will
//!   not change in a `time` release, and a settlement archive whose timestamps
//!   were written by one version and are read by another is a dispute nobody
//!   can resolve. `crate::TariffFingerprint` already refuses to let `time`
//!   format anything it hashes, for exactly this reason; the wire had the same
//!   exposure and no such defence.
//!
//! So every date and instant in a serialisable type goes through this module.
//! `OffsetDateTime` uses `time`'s own RFC 3339 support directly — it is
//! well-known and stable by definition — and [`date`] and [`clock`] are pinned
//! here to the ISO 8601 spellings the same standards use.
//!
//! ```
//! # #[cfg(feature = "serde")] {
//! use emob_core::QuarterHour;
//! use time::macros::datetime;
//!
//! let quarter = QuarterHour::containing(datetime!(2026-01-02 10:07 +1));
//! assert_eq!(
//!     serde_json::to_string(&quarter)?,
//!     r#""2026-01-02T10:00:00+01:00""#,
//! );
//! # }
//! # Ok::<(), Box<dyn std::error::Error>>(())
//! ```

// `date` — a calendar date as `YYYY-MM-DD`: ISO 8601, and what every
// regulator's own document writes. The default is `[year, ordinal]`, which is
// not a date anybody reads.
/// A calendar date as `YYYY-MM-DD` — ISO 8601, and what every regulator's own
/// document writes.
///
/// `time`'s default is `[year, ordinal]`, which is not a date anybody reads.
///
/// Written out rather than generated by `time::serde::format_description!`,
/// which leaves its module private and therefore unusable from the other
/// crates that need to name it in a `serde(with = …)` path.
#[cfg(feature = "serde")]
pub mod date {
    use serde::{Deserialize as _, Deserializer, Serializer, de::Error as _};

    /// The one spelling, pinned here so no dependency chooses it.
    const FORMAT: &[time::format_description::FormatItem<'_>] =
        time::macros::format_description!("[year]-[month]-[day]");

    /// Write a date as `YYYY-MM-DD`.
    ///
    /// # Errors
    ///
    /// Whatever the serializer returns.
    pub fn serialize<S: Serializer>(value: &time::Date, serializer: S) -> Result<S::Ok, S::Error> {
        let text = value
            .format(FORMAT)
            .map_err(|e| serde::ser::Error::custom(e.to_string()))?;
        serializer.serialize_str(&text)
    }

    /// Read one back.
    ///
    /// # Errors
    ///
    /// [`serde::de::Error`] for text that is not a date in this spelling.
    pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<time::Date, D::Error> {
        let text = <std::borrow::Cow<'_, str>>::deserialize(deserializer)?;
        time::Date::parse(&text, FORMAT).map_err(D::Error::custom)
    }

    /// The same, for an optional date.
    pub mod option {
        use serde::{Deserialize as _, Deserializer, Serializer};

        /// Write an optional date, or null.
        ///
        /// # Errors
        ///
        /// Whatever the serializer returns.
        pub fn serialize<S: Serializer>(
            value: &Option<time::Date>,
            serializer: S,
        ) -> Result<S::Ok, S::Error> {
            match value {
                Some(date) => {
                    let text = date
                        .format(super::FORMAT)
                        .map_err(|e| serde::ser::Error::custom(e.to_string()))?;
                    serializer.serialize_some(&text)
                }
                None => serializer.serialize_none(),
            }
        }

        /// Read one back.
        ///
        /// # Errors
        ///
        /// [`serde::de::Error`] for text that is not a date in this spelling.
        pub fn deserialize<'de, D: Deserializer<'de>>(
            deserializer: D,
        ) -> Result<Option<time::Date>, D::Error> {
            use serde::de::Error as _;
            match Option::<std::borrow::Cow<'_, str>>::deserialize(deserializer)? {
                Some(text) => time::Date::parse(&text, super::FORMAT)
                    .map(Some)
                    .map_err(D::Error::custom),
                None => Ok(None),
            }
        }
    }
}

/// A time of day as `HH:MM:SS`.
///
/// Seconds always, rather than only when non-zero: a tariff window written
/// `22:00` on one side and `22:00:00` on the other is one window that compares
/// as two strings in every log and diff it passes through.
#[cfg(feature = "serde")]
pub mod clock {
    use serde::{Deserialize as _, Deserializer, Serializer, de::Error as _};

    /// The one spelling.
    const FORMAT: &[time::format_description::FormatItem<'_>] =
        time::macros::format_description!("[hour]:[minute]:[second]");

    /// Write a time of day as `HH:MM:SS`.
    ///
    /// # Errors
    ///
    /// Whatever the serializer returns.
    pub fn serialize<S: Serializer>(value: &time::Time, serializer: S) -> Result<S::Ok, S::Error> {
        let text = value
            .format(FORMAT)
            .map_err(|e| serde::ser::Error::custom(e.to_string()))?;
        serializer.serialize_str(&text)
    }

    /// Read one back.
    ///
    /// # Errors
    ///
    /// [`serde::de::Error`] for text that is not a time in this spelling.
    pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<time::Time, D::Error> {
        let text = <std::borrow::Cow<'_, str>>::deserialize(deserializer)?;
        time::Time::parse(&text, FORMAT).map_err(D::Error::custom)
    }

    /// The same, for an optional time of day.
    pub mod option {
        use serde::{Deserialize as _, Deserializer, Serializer};

        /// Write an optional time, or null.
        ///
        /// # Errors
        ///
        /// Whatever the serializer returns.
        pub fn serialize<S: Serializer>(
            value: &Option<time::Time>,
            serializer: S,
        ) -> Result<S::Ok, S::Error> {
            match value {
                Some(at) => {
                    let text = at
                        .format(super::FORMAT)
                        .map_err(|e| serde::ser::Error::custom(e.to_string()))?;
                    serializer.serialize_some(&text)
                }
                None => serializer.serialize_none(),
            }
        }

        /// Read one back.
        ///
        /// # Errors
        ///
        /// [`serde::de::Error`] for text that is not a time in this spelling.
        pub fn deserialize<'de, D: Deserializer<'de>>(
            deserializer: D,
        ) -> Result<Option<time::Time>, D::Error> {
            use serde::de::Error as _;
            match Option::<std::borrow::Cow<'_, str>>::deserialize(deserializer)? {
                Some(text) => time::Time::parse(&text, super::FORMAT)
                    .map(Some)
                    .map_err(D::Error::custom),
                None => Ok(None),
            }
        }
    }
}

/// A duration as a whole number of seconds.
///
/// `time::Duration` serialises as `[seconds, nanoseconds]` by default. Every
/// duration this workspace puts on a wire is a session length or a clock
/// resolution — quantities `[REA 6-A §3.1]` and `[AFIR Art. 5(4)]` both discuss
/// in seconds and minutes — so the sub-second half is precision nobody asked
/// for wrapped around a shape nobody can read.
#[cfg(feature = "serde")]
pub mod duration_seconds {
    use serde::{Deserialize as _, Deserializer, Serializer};

    /// Write a duration as its whole seconds.
    ///
    /// # Errors
    ///
    /// Whatever the serializer returns.
    pub fn serialize<S: Serializer>(
        value: &time::Duration,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        serializer.serialize_i64(value.whole_seconds())
    }

    /// Read one back.
    ///
    /// # Errors
    ///
    /// Whatever the deserializer returns.
    pub fn deserialize<'de, D: Deserializer<'de>>(
        deserializer: D,
    ) -> Result<time::Duration, D::Error> {
        i64::deserialize(deserializer).map(time::Duration::seconds)
    }

    /// The same, for an optional duration.
    pub mod option {
        use serde::{Deserialize as _, Deserializer, Serializer};

        /// Write an optional duration as whole seconds, or null.
        ///
        /// # Errors
        ///
        /// Whatever the serializer returns.
        pub fn serialize<S: Serializer>(
            value: &Option<time::Duration>,
            serializer: S,
        ) -> Result<S::Ok, S::Error> {
            match value {
                Some(duration) => serializer.serialize_some(&duration.whole_seconds()),
                None => serializer.serialize_none(),
            }
        }

        /// Read one back.
        ///
        /// # Errors
        ///
        /// Whatever the deserializer returns.
        pub fn deserialize<'de, D: Deserializer<'de>>(
            deserializer: D,
        ) -> Result<Option<time::Duration>, D::Error> {
            Ok(Option::<i64>::deserialize(deserializer)?.map(time::Duration::seconds))
        }
    }
}

/// A weekday by its English name, lower case.
///
/// `time::Weekday` serialises as a bare integer whose base is not stated
/// anywhere a reader of the JSON can see. `[OCPI 2.3.0 §Tariff]` writes the
/// day names, and a tariff restriction is a document a human argues about.
#[cfg(feature = "serde")]
pub mod weekday {
    use serde::{Deserialize as _, Deserializer, Serializer, de::Error as _};

    /// The seven names, in `time::Weekday`'s own order.
    const NAMES: [(&str, time::Weekday); 7] = [
        ("monday", time::Weekday::Monday),
        ("tuesday", time::Weekday::Tuesday),
        ("wednesday", time::Weekday::Wednesday),
        ("thursday", time::Weekday::Thursday),
        ("friday", time::Weekday::Friday),
        ("saturday", time::Weekday::Saturday),
        ("sunday", time::Weekday::Sunday),
    ];

    /// Write a weekday as its name.
    ///
    /// # Errors
    ///
    /// Whatever the serializer returns.
    #[allow(
        clippy::ptr_arg,
        reason = "serde's `with` contract passes the field type by reference, and the field is a Vec"
    )]
    pub fn serialize<S: Serializer>(
        value: &Vec<time::Weekday>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        let names: Vec<&str> = value
            .iter()
            .map(|day| {
                NAMES
                    .iter()
                    .find(|(_, d)| d == day)
                    .map_or("monday", |(name, _)| *name)
            })
            .collect();
        serde::Serialize::serialize(&names, serializer)
    }

    /// Read them back.
    ///
    /// # Errors
    ///
    /// [`serde::de::Error`] for a name outside the seven.
    pub fn deserialize<'de, D: Deserializer<'de>>(
        deserializer: D,
    ) -> Result<Vec<time::Weekday>, D::Error> {
        Vec::<String>::deserialize(deserializer)?
            .into_iter()
            .map(|name| {
                NAMES
                    .iter()
                    .find(|(n, _)| n.eq_ignore_ascii_case(&name))
                    .map(|(_, day)| *day)
                    .ok_or_else(|| D::Error::custom(format!("{name} is not a weekday")))
            })
            .collect()
    }
}

#[cfg(all(test, feature = "serde"))]
mod tests {
    use time::macros::{date, datetime, time as clock_time};

    #[derive(Debug, PartialEq, serde::Serialize, serde::Deserialize)]
    struct Sample {
        #[serde(with = "super::date")]
        on: time::Date,
        #[serde(with = "super::clock::option")]
        from: Option<time::Time>,
        #[serde(with = "super::duration_seconds")]
        lasted: time::Duration,
        #[serde(with = "super::weekday")]
        days: Vec<time::Weekday>,
        #[serde(with = "time::serde::rfc3339")]
        at: time::OffsetDateTime,
    }

    #[test]
    fn every_temporal_field_is_written_in_a_form_a_partner_can_read() {
        let sample = Sample {
            on: date!(2026 - 01 - 02),
            from: Some(clock_time!(22:00)),
            lasted: time::Duration::seconds(1800),
            days: vec![time::Weekday::Monday, time::Weekday::Sunday],
            at: datetime!(2026-01-02 10:00 +1),
        };
        let json = serde_json::to_string(&sample).unwrap();

        assert_eq!(
            json,
            concat!(
                r#"{"on":"2026-01-02","from":"22:00:00","lasted":1800,"#,
                r#""days":["monday","sunday"],"at":"2026-01-02T10:00:00+01:00"}"#,
            ),
            "a partner has to be able to read this without owning our types"
        );
        assert_eq!(serde_json::from_str::<Sample>(&json).unwrap(), sample);
    }

    #[test]
    fn an_absent_time_is_null_rather_than_an_empty_shape() {
        let sample = Sample {
            on: date!(2026 - 01 - 02),
            from: None,
            lasted: time::Duration::ZERO,
            days: Vec::new(),
            at: datetime!(2026-01-02 10:00 UTC),
        };
        let json = serde_json::to_string(&sample).unwrap();
        assert!(json.contains(r#""from":null"#), "{json}");
        assert!(json.contains(r#""at":"2026-01-02T10:00:00Z""#), "{json}");
        assert_eq!(serde_json::from_str::<Sample>(&json).unwrap(), sample);
    }

    #[test]
    fn a_name_outside_the_seven_is_refused() {
        let broken = r#"{"on":"2026-01-02","from":null,"lasted":0,"days":["funday"],"at":"2026-01-02T10:00:00Z"}"#;
        let error = serde_json::from_str::<Sample>(broken).unwrap_err();
        assert!(error.to_string().contains("not a weekday"), "{error}");
    }
}
